name: Build and deploy images

on:
  push:
    branches:
      - master
    paths:
      - build.py
      - config.json
      - tugboat-cli
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to ghcr.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: x-access-token
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and deploy
        shell: bash
        run: |
          python3 build.py
